name: GBA build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cache toolchain
      id: cache-tc
      uses: actions/cache@v3
      with:
        path: /opt/devkitpro
        key: devkitarm-cache1

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev

    - name: install toolchain
      if: steps.cache-tc.outputs.cache-hit != 'true'
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S gba-dev --noconfirm
        sudo chmod -R a+r /opt/devkitpro

    - name: prepare datafiles
      run: |
        svn export svn://mutantstargoat.com/datadirs/voxelburg data

    - name: build
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=/opt/devkitpro/devkitARM
        export PATH=$DEVKITARM/bin:$DEVKITPRO/tools/bin:$PATH
        make

    - uses: actions/upload-artifact@v3
      with:
        name: voxelburg
        path: voxelburg.gba
